Description of global_to_active
Home > NonlinearDyn_vectorialform > Old > global_to_active.m
global_to_active
PURPOSE
SYNOPSIS
function idof = global_to_active(iglob, active)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
equations_linear_vector Equations of the system of the form
equations_vector Equations of the system of the form
linear_solution Real(Xhat) = XcosH1
SOURCE CODE
function idof = global_to_active(iglob, active)
idof = find(~(active-iglob));
end